export default {
  translation: {
    greeting: "Hello",
    // CartScreen
    checkout: "Checkout",
    removeFromCart: "Remove from cart",
    goShop: "Go shop some.",
    cantLoad: "Can't load cart at the moment.",
    cannotRemove: "Cannot remove item.",
    itemRemoved: "Item removed from cart.",
    emptyCart: "Cart is empty.",
    logout: "Logout",
    // Checkout
    orderPlaced: "Order has been placed.",
    cannotOrder: "Cannot place order.",
    summary: "Products summary",
    gTotal: "Grand total",
    placeOrder: "Place Order",
    customer: "Customer details",
    contact: "Contact",
    address: "Address",
    // framerHeader
    searchPlace: "Search Products Here...!",
    // Farmerhome
    sresults: "Search results for",
    myOrders: "My Orders",
    // ProductDescription
    cart: "Add to Cart",
    buy: "BUY NOW",
    description: "Description",
    loginToAdd: "Login to add item to cart.",
    itemAdded: "Item added to cart successfully.",
    cannotAdd: "Cannot add item to cart",
    itemAlready: "Item is already in cart.",
    // ProductCard
    kg: "kg",
    // Farmer Register Page
    phReq: "Phone number is required.",
    paReq: "Password is required.",
    naReq: "Name is required",
    adReq: "Address is required",
    fullName: "Full Name",
    enterFName: "Enter your Full name",
    addr: "Address",
    enterAddr: "Enter your address",
    register: "Register",
    already: "Already have an account? Sign in",
    // Farmer Signin
    farmer: "FARMER",
    phone: "Phone number",
    pass: "Password",
    enterPhone: "Enter your phone number",
    enterPass: "Enter your password",
    login: "LOGIN",
    signUp: "Sign Up",
    forgotPass: "Forgot password?",
    // My Orders
    orderStatus : "Order Status",
    dispatched: "Dispatched",
    trackOrder : "Track Order",
    oProcess : "Order Processed",
    oProcessDesc : "Your Order has been Successfully Processed",
    disDesc: "Your Order is on the way...",
    oRec : "Order Received",
    awaCon : "(Awaiting Confirmation)",
    close : "Close",
    currentOrders: "currentOrders",
    completedOrders : "completedOrders",
    pName : "Product Name",
    tPrice : "Total Price",
  }
};
